### ISSUE TITLE
use datastore-s3

### ISSUE THREAD

**Issue by happy-zhangbo** [ipfs/js-datastore-s3#23]
Class constructor S3Datastore cannot be invoked without 'new'

**Comment by achingbrain** [comment]
It sounds like you're doing something like this:

```javascript
const S3Store = require('datastore-s3')
const store = S3Store(... some options ...)
```

You need to use the `new` keyword:

```javascript
const S3Store = require('datastore-s3')
const store = new S3Store(... some options ...)
```
See the [usage example](https://github.com/ipfs/js-datastore-s3#usage) in the readme.

**Comment by happy-zhangbo** [comment]
> 听起来您正在执行以下操作：
> 
> ```js
> const  S3Store  =  require（' datastore-s3 '）
>  const  store  =  S3Store（...一些选项...）
> ```
> 
> 您需要使用`new`关键字：
> 
> ```js
> const  S3Store  =  require（' datastore-s3 '）
>  const  store  =  new  S3Store（...一些选项...）
> ```
> 
> 请参阅自述文件中的[用法示例](https://github.com/ipfs/js-datastore-s3#usage)。

**Comment by happy-zhangbo** [comment]
thanks

**Comment by achingbrain** [comment]
I think this was reopened by mistake.  Please reopen with more information if you're still having problems with this.
