### ISSUE TITLE
Change key format for better sharding performance

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-datastore-s3#27]
Behind the scenes of a S3 bucket objects are sharded based on their keys when under load.  Shards are created per-prefix and a top level prefix is the characters in the key up to the first delimiter ('/').  Each prefix has a rate limit that will kick in after a certain number of requests to a given prefix.

Our key format is [${path}/${key}](https://github.com/ipfs/js-datastore-s3/blob/master/src/index.js#L55), where `${key}` is a base32 encoded multihash for blocks or a string for datastore keys.  This means if you specify (an optional) path, S3 will try to put all of your data into one shard, killing performance.  If you don't specify a path, S3 will treat all your keys as prefixless and put them in one shard also killing performance.

We can avoid this by dropping the `path` parameter, reversing the key (since the first few characters of a base32 encoded multihash are stable) and adding `/` characters at known locations to create random-ish prefixes (though maybe we only want to do this if we're given a key that can be parsed as a base32 encoded multihash?). Prefix length used to be the first 6-8 characters but TBH it's not clear to me what it is now.

This may help prevent the sort of service degradation 3box [experienced recently](https://medium.com/3box/post-mortem-on-3box-service-degradation-f1da33e582dd) while using this datastore.

Refs:
 - http://highscalability.com/blog/2012/3/7/scale-indefinitely-on-s3-with-these-secrets-of-the-s3-master.html
 - https://aws.amazon.com/blogs/aws/amazon-s3-performance-tips-tricks-seattle-hiring-event/
 - https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html
 - https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-s3-announces-increased-request-rate-performance/
 - https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys

**Comment by achingbrain** [comment]
cc: @oed - you've mentioned S3 sharding in the post-mortem linked to above - would this sort of change have helped prevent the service degradation you encountered?

**Comment by oed** [comment]
I will let @zachferland weigh in more here, but just our initial findings when looking at this is that if you use ´datastore-fs´, that is default in the nodejs runtime, the "sharding" flag will be enabled in `ipfs-repo`. This flag essentially takes the two last characters of the *base32* multihash and uses them as folders. When we started using S3 as a backend using `datastore-s3` this "sharding" flag got disabled. I think the problem could be solved fairly trivially by simply enabling the sharding flag when using `datastore-s3` as well.

**Comment by achingbrain** [comment]
It sounds like this datastore needs to have sharding turned on by default, which will require a major release and some sort of update script.

Sharding is [turned on by default](https://github.com/ipfs/js-ipfs-repo/blob/33663b31ce2fd305c8d30962c9b1de6d20f96114/src/default-options.js#L16-L19) for blocks in ipfs-repo but not for other stores and [not in the browser](https://github.com/ipfs/js-ipfs-repo/blob/33663b31ce2fd305c8d30962c9b1de6d20f96114/src/default-options-browser.js).

In this datastore it's pretty essential and there's doesn't seem to be a good reason not to have sharding turned on.

I'm going to close this issue because the solution I've outlined above isn't the right one - we just need to wrap the datastore in a [ShardingDatastore](https://github.com/ipfs/js-datastore-core/blob/master/src/sharding.js) at the repo level.
