### ISSUE TITLE
Add `ci` team with `write` access

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-datastore-s3#3]
Currently, Jenkins can't set the status of the commits or PRs, because the CI team has not been added with `write` access to this repository.

Once that's done, CI should work perfectly here!

**Comment by jacobheun** [comment]
@diasdavid can you assist with the team permissions for this?

**Comment by diasdavid** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1211152/38539156-e10c69f6-3cd1-11e8-9a1a-9d25ffefbb4b.png">

done :)
