### ISSUE TITLE
Add verbose logging to error states

### ISSUE THREAD

**Issue by v-stickykeys** [ipfs/js-datastore-s3#31]
```
"datastore-s3": "^3.0.0",
"aws-sdk": "^2.782.0"
```

We are creating s3 backed ipfs repo like so

```js
const repo = createRepo({
            path: IPFS_PATH,
        }, {
            bucket: AWS_BUCKET_NAME,
            region: AWS_REGION,
            accessKeyId: AWS_ACCESS_KEY_ID,
            secretAccessKey: AWS_SECRET_ACCESS_KEY,
        })
```

We have been setting path like this `path: "ipfs"` and had no problems... until today!

----

Today we started getting this error..
```
NoSuchKey: The specified key does not exist.
    at Request.extractError (/ipfs/node_modules/aws-sdk/lib/services/s3.js:700:35)
    at Request.callListeners (/ipfs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/ipfs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/ipfs/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/ipfs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/ipfs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /ipfs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/ipfs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/ipfs/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/ipfs/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ERR_NOT_FOUND',
  region: null,
  time: 2021-01-22T20:14:31.610Z,
  requestId: 'REDACTED',
  extendedRequestId: 'REDACTED',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 7.160313735941037
}
```

1. It would be *supremely* helpful if you could add the bucket, key, and region of the request in the logs. (Would have saved me a few hours today 😄): https://github.com/ipfs/js-datastore-s3/blob/master/src/index.js#L234-L252 
2. The key is being retrieved incorrectly. It should be `<bucket>/<key>` but it is currently just `<key>` (So says our AWS cloudtrail logs)
```json
    "eventSource": "s3.amazonaws.com",
    "eventName": "HeadObject",
    "errorCode": "NoSuchKey",
    "errorMessage": "The specified key does not exist.",
    "requestParameters": {
        "bucketName": "ceramic-dev-cas-ipfs-module",
        "Host": "ceramic-dev-cas-ipfs-module.s3.REDACTED.amazonaws.com",
        "key": "ipfs"
    },
```

To fix this we now pass `path: "ceramic-dev-cas-ipfs-module/ipfs"` and it works!

Guessing there was an update with `aws-sdk` that causes this?

**Comment by valmack** [comment]
Update here: My solution just created a new key in the bucket.

So the existing key was `ipfs` and the new key became `<bucket_name>/ipfs`.

Also I am only seeing this NoSuchKey error on some of my S3 buckets. However all of them definitely have a key ipfs so now I'm just not sure what is wrong.

**Comment by valmack** [comment]
I was able to get to the bottom of this 😅 . The S3 bucket was missing `ipfs/version` file. It's a mystery to me why this file was not created in all buckets but was in some... but I guess that is a problem for a different repo

**Comment by jacobheun** [comment]
Glad you were able to figure that out, happy to take PRs in areas that would have been helpful for you to diagnose this.

**Comment by achingbrain** [comment]
Closing as this issue is very old.  Please open a PR against https://github.com/ipfs/js-stores if you'd like this feature to be added.
