### ISSUE TITLE
S3 as a datastore for IPFS

### ISSUE THREAD

**Issue by javiertc** [ipfs/js-datastore-s3#39]
Hi, 

I would like to use S3 as a datastore for my IPFS nodes. I need some help with this questions, if someone can help me that will be great. 

- In order to use js-datastore-S3 I need to have the app running as a service? 

- How is the configuration for the ipfs daemon to use this datastore?

**Comment by lidel** [comment]
@javiertc :pray: use  https://discuss.ipfs.io for support qustions like this, more people will be able to help you :+1: 
ps. I think the example you look for is in https://github.com/ipfs/js-datastore-s3/tree/master/examples/full-s3-repo
