### ISSUE TITLE
AWS SDK v3

### ISSUE THREAD

**Issue by willfarrell** [ipfs/js-datastore-s3#81]
As of the NodeJS v18 AWS Lambda runtime, AWS SDK v2 will be deprecated for AWS SDK v3 within the runtime itself. Upgrading to v3 should be pretty straight forward. Is there interest from the IPFS team to make this breaking change if a PR is put together?

**Comment by achingbrain** [comment]
See the comment on #85 - the aws sdk was updated in #106.

So sorry I missed your PR and thanks so much for putting the time in to start doing the upgrade.

Please open issues on https://github.com/ipfs/js-stores if you find issues with the new release!
